apiVersion: v1
kind: Service
metadata:
  name: "devops-svc-alb-api"
  namespace: "devops-alb"
spec:
  selector:
    app: "devops-deploy-alb-api"
  type: NodePort
  ports:
    - name: web
      port: 8090
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: "devops"
  name: "devops-deploy-alb-api"
  namespace: "devops-alb"
spec:
  selector:
    matchLabels:
      app: "devops-deploy-alb-api"
  replicas: 1
  template:
    metadata:
      labels:
        app: "devops-deploy-alb-api"
    spec:
      containers:
      - name: "devops"
        image: navikt/arxaas
        ports:
          - containerPort: 8080
        # command:
        #   - "sh"
        #   - "-c"
        #   - "yum install -y python3-pip && tail -f /var/log/yum.log "
        resources:
          limits:
            memory: "500Mi"
            cpu: "0.25"
